name: TodoList
options:
  bundleIdPrefix: com.todolist
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  TodoList:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - "**/.gitignore"
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.todolist.app
        PRODUCT_NAME: TodoList
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_CFBundleDisplayName: TodoList
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_HARDENED_RUNTIME: NO
